project:
  type: website
  output-dir: docs

website:
  title: "Brady Kennedy"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Portfolio
        href: portfolio.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
